services:
  # Static Web App Service
  - type: web
    name: pmp-app
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    publishDir: frontend/out
    plan: free
    region: oregon
